# LFS Build Tools Package
# This package contains Starlark rules for building LFS packages

# Export the build rules for use by other packages
exports_files([
    "lfs_build.bzl",
    "providers.bzl",
])
